defmodule RandomWords.Helpers do
  defmacro pos_helper(pos) do
    quote do
      @doc """
      Returns a single word of type: #{unquote(pos)}

      *Autogenerated function*
      """
      @spec unquote(pos)() :: String.t()
      def unquote(pos)(), do: word(part_of_speech: unquote(pos))
    end
  end
end
